### ISSUE TITLE
Update license please

### ISSUE THREAD

**Issue by burdickjp** [kurt-schaefer/owl-clock#1]
Hey, Kurt!
I want to make DROs for me mill and lathe using plexitubes because they're awesome. I appreciate that you've got a github for the project, because it allows me to link back to it and provide proper attribution.
I noticed that your license is software related and this is a hardware project.
Could you switch to a license compliant with the open source hardware guidelines?
http://www.oshwa.org/

I tend to use the Cern OHL:
http://www.ohwr.org/projects/cernohl/wiki

Thank you, again for documenting such an awesome project and taking the time to releasing it as open source.

**Comment by kurt-schaefer** [comment]
Wow, I'd love to see a mill with Plexitube DRO's!   That sounds fun.   Yes sorry I was mostly using github for the software side.  I've never released open source hardware before.  I'll read though the guidelines and update the license.  I wrote the build up as a "oh I built this" not as a full on "here's every detail on how to built it yourself".  So just be aware of that.   Refining/documenting/testing a project to a "this is DIY instructions" level is a  project unto itself.  Doing these Christmas Projects I always have a super short schedule so time for iteration is pretty much zero.  

Let me know if you manage to get something up and running!   If you get it written up I'd be happy to add a link over to it from my blog. I'd love to see some other projects spring from this one. 

I'm super busy right this second, but Wed. night I should have time to read up on the license stuff and update it.  I should know about that stuff anyway since I do a modest amount of hardware design.

**Comment by burdickjp** [comment]
Thank you, and glad I can help with the licensing.
Looking through Oshwa can be daunting, but in general it just comes down to a preference for working files rather than distribution files. A good example is CAD models rather than STLs for 3d printing parts. STEP files are a good compromise because they can be altered by most CAD programs, but STLs are lossy and don't preserve features.
If you're worried front-to-back about a permissive license which provides a decent blanket to all things you could go with a creative commons license. I prefer stricter OHL licenses because of their focus on releasing working, usable models.

**Comment by kurt-schaefer** [comment]
Ok, I added the cernohl.  Let me know how your project goes!
